### ISSUE TITLE
Could you please make standard Sitecore package for sample?

### ISSUE THREAD

**Issue by Artyom-ARS** [asmagin/sitecore-js-presentation#8]
Could you please make standard Sitecore package for sample?
Your sample package is using TDS serialization format and it's not possible o install it without TDS.

**Comment by asmagin** [comment]
There is no such thing as TDS serialization format as TDS is using Sitecore format. The package included in the sample should be installed via **Update Installation Wizard**. You can find it via this URL: http://your-Sitecore-website-here/sitecore/admin/UpdateInstallationWizard.aspx.

**Comment by Artyom-ARS** [comment]
Thank you for the explanation.
